"use client";

import { type FormEvent, useState } from "react";
import { Check, ExternalLink, Search, X } from "lucide-react";
import { Button, Card } from "@/components/ui";
import { useCandidates, useDiscoverCompanies, useReviewCandidate } from "@/hooks/use-admin";

export function AdminPage() {
  const [sector, setSector] = useState("Dairy Processing");
  const [country, setCountry] = useState("Germany");
  const candidates = useCandidates(); const discover = useDiscoverCompanies(); const review = useReviewCandidate();
  const submit = (event: FormEvent) => { event.preventDefault(); discover.mutate({ sector, country }); };
  return <div className="mx-auto max-w-6xl space-y-8"><div><p className="text-sm font-medium text-cyan-300">Admin workspace</p><h1 className="mt-2 text-3xl font-semibold text-white">Company discovery and review</h1><p className="mt-2 text-zinc-400">Review evidence before a company is added to the directory and indexed for Ask AI.</p></div><Card className="hover:translate-y-0"><form onSubmit={submit} className="grid gap-4 md:grid-cols-[1fr_1fr_auto]"><input value={sector} onChange={(e) => setSector(e.target.value)} placeholder="Sector" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none" /><input value={country} onChange={(e) => setCountry(e.target.value)} placeholder="Country" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none" /><Button disabled={discover.isPending}><Search className="h-4 w-4" />{discover.isPending ? "Discovering" : "Discover"}</Button></form>{discover.isError ? <p className="mt-4 text-sm text-red-300">Discovery failed. Verify the AI services and try again.</p> : null}</Card><section className="space-y-4"><h2 className="text-xl font-semibold text-white">Candidates</h2>{candidates.isLoading ? <p className="text-zinc-400">Loading candidates...</p> : candidates.data?.length ? candidates.data.map((candidate) => <Card key={candidate.id} className="hover:translate-y-0"><div className="flex flex-col justify-between gap-5 md:flex-row"><div><div className="flex items-center gap-3"><h3 className="text-lg font-semibold text-white">{candidate.name}</h3><span className="rounded-full bg-cyan-400/10 px-2 py-1 text-xs text-cyan-300">{Math.round(candidate.confidence_score * 100)}% confidence</span><span className="text-xs uppercase text-zinc-500">{candidate.status}</span></div><p className="mt-2 text-sm text-zinc-400">{candidate.category} · {candidate.country}</p><p className="mt-3 text-sm text-zinc-300">{candidate.use_cases}</p><div className="mt-4 space-y-2">{candidate.evidence.map((evidence) => <a key={evidence.url} href={evidence.url} target="_blank" rel="noreferrer" className="block rounded-lg bg-black/20 p-3 text-sm text-zinc-300 hover:text-cyan-300"><span className="font-medium">{evidence.source}</span>: {evidence.snippet} <ExternalLink className="ml-1 inline h-3.5 w-3.5" /></a>)}</div></div>{candidate.status === "pending" ? <div className="flex shrink-0 gap-2"><Button onClick={() => review.mutate({ id: candidate.id, action: "approve" })}><Check className="h-4 w-4" />Approve</Button><button onClick={() => review.mutate({ id: candidate.id, action: "reject" })} className="rounded-xl border border-white/10 px-4 text-sm text-zinc-300 hover:border-red-400/40"><X className="inline h-4 w-4" /> Reject</button></div> : null}</div></Card>) : <p className="text-zinc-400">No candidates yet. Start a discovery search above.</p>}</section></div>;
}
