"""add full text search vector

Revision ID: 691a3db1a542
Revises: 862b05f714bc
Create Date: 2026-07-18 19:39:16.837314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '691a3db1a542'
down_revision: Union[str, Sequence[str], None] = '862b05f714bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=False))
    op.drop_constraint(op.f('embeddings_chunk_id_key'), 'embeddings', type_='unique')
    op.drop_index(op.f('idx_embeddings_hnsw'), table_name='embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('idx_embeddings_hnsw'), 'embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_unique_constraint(op.f('embeddings_chunk_id_key'), 'embeddings', ['chunk_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('embeddings', 'search_vector')
    # ### end Alembic commands ###
